//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musica12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MUSIC
    {
        public int Idmusica { get; set; }
        public string titulo { get; set; }
        public string autor { get; set; }
        public string album { get; set; }
        public string genero { get; set; }
        public int fecha_lanzamiento { get; set; }
        public string duracion { get; set; }
    }
}
